export const orderTypes = {
    CREATE_ORDER_START:"CREATE_ORDER_START",
    CREATE_ORDER_SUCCESS:"CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAIL:"CREATE_ORDER_FAIL",

    DETAILS_ORDER_START:"DETAILS_ORDER_START",
    DETAILS_ORDER_SUCCESS:"DETAILS_ORDER_SUCCESS",
    DETAILS_ORDER_FAIL:"DETAILS_ORDER_FAIL",

    GET_ORDERS_START:"GET_ORDERS_START",
    GET_ORDERS_SUCCESS:"GET_ORDERS_SUCCESS",
    GET_ORDERS_FAIL:"GET_ORDERS_FAIL",

    PAY_ORDER_START:"PAY_ORDER_START",
    PAY_ORDER_SUCCESS:"PAY_ORDER_SUCCESS",
    PAY_ORDER_FAIL:"PAY_ORDER_FAIL",
    
    DELIVERED_ORDER_START:"DELIVERED_ORDER_START",
    DELIVERED_ORDER_SUCCESS:"DELIVERED_ORDER_SUCCESS",
    DELIVERED_ORDER_FAIL:"DELIVERED_ORDER_FAIL",

    RESET_ORDER:"RESET_ORDER",
}
