
export const userTypes = {
    USER_START:"USER_START",
    USER_SUCESS:"USER_SUCESS",
    USER_FAIL:"USER_FAIL",

    GET_USER_START:"GET_USER_START",
    GET_USER_SUCCESS:"GET_USER_SUCCESS",
    GET_USER_FAIL:"GET_USER_FAIL",

    LOGOUT:"LOGOUT",


    UPDATE_USER_START:"UPDATE_USER_START",
    UPDATE_USER_SUCESS:"UPDATE_USER_SUCESS",
    UPDATE_USER_FAIL:"UPDATE_USER_FAIL",
    
    LIST_USERS_START:"LIST_USERS_START",
    LIST_USERS_SUCESS:"LIST_USERS_SUCESS",
    LIST_USERS_FAIL:"LIST_USERS_FAIL",
    
    DELETE_USER_START:"DELETE_USER_START",
    DELETE_USER_SUCESS:"DELETE_USER_SUCESS",
    DELETE_USER_FAIL:"DELETE_USER_FAIL",

    ADMIN_GET_USER_START:"ADMIN_GET_USER_START",
    ADMIN_GET_USER_SUCESS:"ADMIN_GET_USER_SUCESS",
    ADMIN_GET_USER_FAIL:"ADMIN_GET_USER_FAIL",

    ADMIN_UPDATE_USER_START:"ADMIN_UPDATE_USER_START",
    ADMIN_UPDATE_USER_SUCESS:"ADMIN_UPDATE_USER_SUCESS",
    ADMIN_UPDATE_USER_FAIL:"ADMIN_UPDATE_USER_FAIL",
}
