export const productTypes = {
    FETCH_PRODS_START:'FETCH_PRODS_START',
    FETCH_PRODS_SUCCESS:'FETCH_PRODS_SUCCESS',
    FETCH_PRODS_FAILURE:'FETCH_PRODS_FAILURE',
   
    CREATE_PRODS_START:'CREATE_PRODS_START',
    CREATE_PRODS_SUCCESS:'CREATE_PRODS_SUCCESS',
    CREATE_PRODS_FAILURE:'CREATE_PRODS_FAILURE',
    RESET_PRODS:'RESET_PRODS',
   
    UPDATE_PRODS_START:'UPDATE_PRODS_START',
    UPDATE_PRODS_SUCCESS:'UPDATE_PRODS_SUCCESS',
    UPDATE_PRODS_FAILURE:'UPDATE_PRODS_FAILURE',
   
    DELETE_PRODS_START:'DELETE_PRODS_START',
    DELETE_PRODS_SUCCESS:'DELETE_PRODS_SUCCESS',
    DELETE_PRODS_FAILURE:'FETCH_PRODS_FAILURE',
   
    REVIEW_PRODS_START:'REVIEW_PRODS_START',
    REVIEW_PRODS_SUCCESS:'REVIEW_PRODS_SUCCESS',
    REVIEW_PRODS_FAILURE:'REVIEW_PRODS_FAILURE',
   
    TOP_PRODS_START:'TOP_PRODS_START',
    TOP_PRODS_SUCCESS:'TOP_PRODS_SUCCESS',
    TOP_PRODS_FAILURE:'TOP_PRODS_FAILURE',
}